server:
  http_listen_port: 9080

clients:
  - url: http://loki:3100/api/prom/push

scrape_configs:
  - job_name: 'fastapi-logs'
    static_configs:
      - targets:
          - localhost
        labels:
          job: fastapi
          __path__: /var/lib/docker/containers/*/*.log  
    pipeline_stages:
      - docker: {}  
